log in test
ausraurnezaite/FinalTask pull request #1
Opened 2022-08-05 08:59 UTC by ausraurnezaite

2022-08-05 10:30 UTC, shukal94 requested changes
1) inheritance - 'IS A' kind of relation between the classes, Page is not DriverManager, if you want to use driver inside the page let's pass it as a constructor param, then we'll have Page HAS A driver, which is more valid
2) let's have BasePage class with a basic constructor which will init page elements (via super call)
3) 
example of props
browser=chrome
env=grid
saucelabs.chrome.browser.version=103
saucelabs.chrome.brower.platform=WINDOWS
saucelabs.firefox.browser.version=103
saucelabs.firefox.brower.platform=WINDOWS
grid.firefox.browser.version=103
grid.firefox.brower.platform=WINDOWS

2022-08-05 10:30 UTC, shukal94 commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/LogInPage.java
> +    private final String LOGIN_PAGE_LINK = "http://automationpractice.com/index.php?controller=authentication&back=my-account";
let's have those variables in the test class, make your page methods flexible as much as possible

2022-08-05 10:30 UTC, shukal94 commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/MainPage.java
> +    private final String TITLE = "My Store";
do not see any usage

2022-08-05 10:30 UTC, shukal94 commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/RegistrationPage.java
> +    private final String PASSWORD = PropertyProvider.getProperty("password");
see above

2022-08-05 10:30 UTC, shukal94 commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/RegistrationPage.java
> +        postalInput.sendKeys("12345");
can we randomise?
for the complex forms let's have a page pojo which will have the params you want to send into page
hint - use factory method to generate those fields data

2022-08-05 10:30 UTC, shukal94 commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/util/DriverManager.java
> +//    public static void setDriverToContext(ITestContext iTestContext, WebDriver driver) {
remove dead code

2022-08-05 10:30 UTC, shukal94 commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/util/PropertyProvider.java
> +        try (InputStream input = new FileInputStream("src/main/resources/properties.properties")) {
move path to constant

2022-08-05 10:30 UTC, shukal94 commented on src/main/resources/properties.properties
> +password=testaccount
store the passwords in env variables

2022-08-05 10:30 UTC, shukal94 commented on src/main/resources/properties.properties
> +browser=chrome
let's have name like test.properties

2022-08-10 22:01 UTC, KBugrimCS commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/BasePage.java
> +    WebElement myAccountButton;
Do not forget about encapsulation. These fields should have private access modifier

2022-08-10 22:02 UTC, KBugrimCS commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/BasePage.java
> +
Please use formatter. Blank line should be removed

2022-08-10 22:04 UTC, KBugrimCS commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/CartPage.java
> +        List<WebElement> cartItems = driver.findElements(By.cssSelector("td.cart_description"));
Please move this List of elements to fields of this class(page)

2022-08-10 22:07 UTC, KBugrimCS commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/CartPage.java
> +        namesOfItemsInCart.forEach(System.out::println);
Please replace all System.out.println methods in the project to Logger(log4j, log4j2 or logback) for logging

2022-08-10 22:13 UTC, KBugrimCS commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/ItemPage.java
> +    private String itemsReference;
no need to create fields of the class in this case. You can create variables directly in methods where you use them

2022-08-10 22:21 UTC, KBugrimCS commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/ItemPage.java
> +    }
too complicated methods and methods name doesn't match with logic in these methods. I advice you do not create  methods with difficult logic. Usually in automation 95% of all methods on pages are very simple and contain  1-3 lines of code

2022-08-10 22:21 UTC, KBugrimCS commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/ItemPage.java
> +        wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("a.fancybox-close"))).click();
all locators should be declared as a field of class

2022-08-10 22:22 UTC, KBugrimCS commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/ItemPage.java
> +    }
public String getItemsReference() {
        return  itemsReferenceElement.getText();
    }

2022-08-10 22:23 UTC, KBugrimCS commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/LogInPage.java
> +    private WebElement loginButton;
do not forget about formatter

2022-08-10 22:29 UTC, KBugrimCS commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/MainPage.java
> +        Integer random = new Faker().random().nextInt(1, products.findElements(By.cssSelector("li")).size());
all locators should be declared as a field of the class

2022-08-10 22:32 UTC, KBugrimCS commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/MyAccountPage.java
> +    private final String TITLE = "My account - My Store";
static

2022-08-10 22:34 UTC, KBugrimCS commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/RegistrationPage.java
> +    private WebElement registerButton;
unreadable. Please use formatter

2022-08-10 22:36 UTC, KBugrimCS commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/RegistrationPage.java
> +        UserData user = UserDataGenerator.generate();
User should be passed to this method as a parameter from test. No need to generate it on the page. Test data should be generated in test

2022-08-10 22:37 UTC, KBugrimCS commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/RegistrationPage.java
> +        registerButton.click();
Please empty line between each 4-6 lines of code for better readability

2022-08-10 22:39 UTC, KBugrimCS commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/RegistrationPage.java
> +        passwordInput.sendKeys(PASSWORD);
password should be taken from UserData instance. no need to read this property on the page

2022-08-10 22:40 UTC, KBugrimCS commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/WishlistPage.java
> +        List<WebElement> wishListElements = wishlistArea.findElements(By.cssSelector("table"));
please declare it as field of class

2022-08-10 22:41 UTC, KBugrimCS commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/WishlistPage.java
> +    }
You have the same method in the base page

2022-08-10 22:43 UTC, KBugrimCS commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/WishlistPage.java
> +        driver.findElement(By.xpath("//a[contains(text(), '" + defaultWishlistName + "')]")).click();
Please use String.format

2022-08-10 22:47 UTC, KBugrimCS commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/factory/UserData.java
> +    }
it's not a builder pattern, please take a look documentations how it works

2022-08-10 22:51 UTC, KBugrimCS commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/factory/UserData.java
> +package com.coherensolutions.training.automation.java.web.urnezaite.factory;
Why did you call this package as factory?

2022-08-10 22:54 UTC, KBugrimCS commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/util/FailedTestListener.java
> +        File destFile = new File("./Screenshots/" + screenshotsSubFolderName + "/" + fileName);
Please use String.format() for generating path

2022-08-10 22:55 UTC, KBugrimCS commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/util/FailedTestListener.java
> +            e.printStackTrace();
please use logger instead of it

2022-08-10 22:55 UTC, KBugrimCS commented on src/main/java/com/coherensolutions/training/automation/java/web/urnezaite/util/GridStrategy.java
> +            e.printStackTrace();
the same as above

2022-08-10 23:01 UTC, KBugrimCS commented on src/test/java/com/coherensolutions/training/automation/java/web/urnezaite/BaseTest.java
> +    final String LOGIN_PAGE_LINK = "http://automationpractice.com/index.php?controller=authentication&back=my-account";
static and add access modifier

2022-08-10 23:02 UTC, KBugrimCS commented on src/test/java/com/coherensolutions/training/automation/java/web/urnezaite/BaseTest.java
> +    final String LOGIN_PAGE_LINK = "http://automationpractice.com/index.php?controller=authentication&back=my-account";
move this link .properties

2022-08-11 21:08 UTC, KBugrimCS commented on logs/testLog.log
> +2022-08-11 16:42:32 INFO  - items in cart: [demo_1, demo_6, demo_3]
please add this package to gitignore too

2022-08-11 21:10 UTC, KBugrimCS commented on src/main/java/com/coherentsolutions/training/automation/java/web/urnezaite/CartPage.java
> +    List<WebElement> cartItems;
private

2022-08-11 21:15 UTC, KBugrimCS commented on src/main/java/com/coherentsolutions/training/automation/java/web/urnezaite/CartPage.java
> +    private List<String> namesOfItemsInCart = new ArrayList<>();
why do you create the field of the class if you use it only in on method? You can create this variable in the method and there

2022-08-11 21:16 UTC, KBugrimCS commented on src/main/java/com/coherentsolutions/training/automation/java/web/urnezaite/CartPage.java
> +    public boolean checkIfItemsWereAddedToCart(List<String> itemsAddedToCart) {
please rename method name according to java code convention for methods that returns boolean value

2022-08-11 21:19 UTC, KBugrimCS commented on src/main/java/com/coherentsolutions/training/automation/java/web/urnezaite/util/Log.java
> +}
no need to create your own Logger, please take a look an example how to use logger https://mkyong.com/logging/apache-log4j-2-tutorials/

2022-08-11 21:23 UTC, KBugrimCS commented on src/main/java/com/coherentsolutions/training/automation/java/web/urnezaite/MainPage.java
> +        WebElement randomItem = products.findElement(By.xpath(String.format("//li[%s]//a[@class='product-name']", random)));
can we create a WebElement list of products and choose some random product from this list?

2022-08-11 21:24 UTC, KBugrimCS commented on src/main/java/com/coherentsolutions/training/automation/java/web/urnezaite/RegistrationPage.java
> +        Log.info(user.toString());
need to create instance of a Logger in the class

2022-08-11 21:25 UTC, KBugrimCS commented on src/main/java/com/coherentsolutions/training/automation/java/web/urnezaite/WishlistPage.java
> +    WebElement deleteWishlistIcon;
private

2022-08-11 21:26 UTC, KBugrimCS commented on src/main/java/com/coherentsolutions/training/automation/java/web/urnezaite/WishlistPage.java
> +    private final By deleteWishlistIconSelector = By.cssSelector("td.wishlist_delete>a.icon");
Need to create instance of WebElement instead of By

2022-08-11 21:28 UTC, KBugrimCS commented on src/main/java/com/coherentsolutions/training/automation/java/web/urnezaite/WishlistPage.java
> +        return wishlistEmpty;
return wishlistLists.size() == 0;

2022-08-11 21:28 UTC, KBugrimCS commented on src/main/java/com/coherentsolutions/training/automation/java/web/urnezaite/WishlistPage.java
> +    List<WebElement> wishlistLists;
weird name of the field

2022-08-11 21:29 UTC, KBugrimCS commented on src/main/java/com/coherentsolutions/training/automation/java/web/urnezaite/WishlistPage.java
> +    public boolean wishlistEmpty;
please remove this field

2022-08-11 21:29 UTC, KBugrimCS commented on src/main/java/com/coherentsolutions/training/automation/java/web/urnezaite/WishlistPage.java
> +        wishlistEmpty = wishlistLists.size() == 0;
no need to init this value in the constructor

2022-08-11 21:31 UTC, KBugrimCS commented on src/main/java/com/coherentsolutions/training/automation/java/web/urnezaite/util/PropertyProvider.java
> +            ex.printStackTrace();
logger

2022-08-11 21:34 UTC, KBugrimCS requested changes
please review my comments and correct them in your code everywhere, because there are so many common mistakes and I didn't leave the same comments in all places

2022-08-15 09:15 UTC, KBugrimCS commented on src/main/java/com/coherentsolutions/training/automation/java/web/urnezaite/BasePage.java
> +    public WebDriver driver;
Better to make it protected

2022-08-15 09:18 UTC, KBugrimCS commented on src/main/java/com/coherentsolutions/training/automation/java/web/urnezaite/HomePage.java
> +    }
you have the same method  with the same implementation in the base class

2022-08-15 09:19 UTC, KBugrimCS commented on src/main/java/com/coherentsolutions/training/automation/java/web/urnezaite/HomePage.java
> +    public CartPage goToCartPage() {
you have the same method with the same implementation in the base class

2022-08-15 09:19 UTC, KBugrimCS commented on src/main/java/com/coherentsolutions/training/automation/java/web/urnezaite/WishlistPage.java
> +    public CartPage goToCartPage() {
you have the same method with the same implementation in the base class

2022-08-15 09:30 UTC, KBugrimCS commented on src/main/java/com/coherentsolutions/training/automation/java/web/urnezaite/MyAccountPage.java
> +    }
What's happen here if selenium doesn't find element? We will get NoSuchElement exception

2022-08-15 09:32 UTC, KBugrimCS commented on src/main/java/com/coherentsolutions/training/automation/java/web/urnezaite/util/FailedTestListener.java
> +            captureScreenshot(testResult.getTestContext().getSuite().getName() + "_" + testResult.getTestContext().getName() + "_" + testResult.getName() + ".png", driver);
Please use String.format here

2022-08-15 09:35 UTC, KBugrimCS commented on src/main/java/com/coherentsolutions/training/automation/java/web/urnezaite/util/FailedTestListener.java
> +            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("ddMMyyy.HHmmss");
Please move this "ddMMyyy.HHmmss" value to a constant, do not hardcode it

2022-08-15 09:35 UTC, KBugrimCS commented on src/main/java/com/coherentsolutions/training/automation/java/web/urnezaite/util/FailedTestListener.java
> +        File destFile = new File("./Screenshots/" + screenshotsSubFolderName + "/" + fileName);
String.format

2022-08-15 09:35 UTC, KBugrimCS commented on src/main/java/com/coherentsolutions/training/automation/java/web/urnezaite/util/FailedTestListener.java
> +        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm:ss");
move to constant

2022-08-15 09:37 UTC, KBugrimCS commented on src/test/java/com/coherentsolutions/training/automation/java/web/urnezaite/BaseTest.java
> +    public MyAccountPage logIn() {
protected

2022-08-15 09:39 UTC, KBugrimCS commented on src/test/java/com/coherentsolutions/training/automation/java/web/urnezaite/CartTest.java
> +        }
please move this logic to a page. Tests should be as abstract and simple as possible. Even a person who does not understand anything in the automation should read the test and understand what is happening there.

2022-08-22 10:28 UTC, KBugrimCS approved these changes

2022-08-22 10:29 UTC, merged